"""empty message

Revision ID: b42b5e39f424
Revises: None
Create Date: 2016-07-08 19:11:02.500812

"""

# revision identifiers, used by Alembic.
revision = 'b42b5e39f424'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirement', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.String(length=200), nullable=True),
    sa.Column('contract_type', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    op.drop_table('advertise')
    ### end Alembic commands ###
